nacos:
  test: dev
spring:
  datasource:
    url: jdbc:mysql://clw-zealot:53306/study?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: zealot
    password: zealot.group
  redis:
    host: clw-zealot
    port: 56379
    password: zealot.group
  activemq:
    user: zealot
    password: zealot.group
    broker-url: tcp://clw-zealot:61616
rocketmq:
  namesrv-addr: clw-zealot:59876
  producer-group: G1
  consumer-group: G1
