spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: zealot
    password: zealot
  redis:
    host: 127.0.0.1
    port: 6379
    password: zealot
  activemq:
    user: zealot
    password: zealot
    broker-url: tcp://127.0.0.1:61616