spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      auto-commit: false
      idle-timeout: 60000
      pool-name: hikariPool
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1