spring:
  datasource:
    url: jdbc:mysql://www.zealot.group:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: zealot
    password: zealot
  redis:
    host: www.zealot.group
    port: 6379
    password: zealot
  activemq:
    user: zealot
    password: zealot
    broker-url: tcp://www.zealot.group:61616