spring:
  datasource:
    url: jdbc:mysql://clw-zealot:53306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: zealot
    password: zealot.group
  redis:
    host: clw-zealot
    port: 56379
    password: zealot.group
  activemq:
    user: zealot
    password: zealot.group
    broker-url: tcp://clw-zealot:61616